#!/bin/bash

cd /tmp/ci/sync/

git clone https://github.com/Thagoo/android_vendor_xiaomi_rolex -b 11 vendor/xiaomi/rolex
git clone https://github.com/Thagoo/android_device_xiaomi_rolex -b 11 device/xiaomi/rolex
git clone https://github.com/Thagoo/platform_kernel_xiaomi_msm8917 -b lineage-18.1 kernel/xiaomi/msm8917

. build/envsetup.sh
lunch lineage_rolex-userdebug
make api-stubs-docs
make hiddenapi-lists-docs
make system-api-stubs-docs
make test-api-stubs-docs
mka bacon -j69
