#!/bin/bash

url=https://cheems.mirrorbomt.workers.dev/superior-ccache.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf superior-ccache.tar.gz
echo "unzip done"
find superior-ccache.tar.gz -delete
