#!/bin/bash

mkdir /tmp/ci/sync/ && cd /tmp/ci/sync/ 
chmod -R 0777 .

export ARCH_ARM_HAVE_TLS_REGISTER=true
export TARGET_CPU_SMP=true
export WITH_JIT=true
export JS_ENGINE=v8 
export USE_CCACHE=1
ccache -M 200G

repo init -q --no-repo-verify -u https://github.com/ProjectSakura/android.git -b 11 --depth=1 --groups=all,-notedefault,-device,-darwin,-x86,-mips
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j48 -q 
