#!/bin/bash

mkdir -p /tmp/rom
cd /tmp/rom
chmod -R 0777 .

rm -rf .repo &

sudo apt-get install -y wget

repo init -q --no-repo-verify -u https://github.com/Havoc-OS/android_manifest.git -b eleven --depth=1 --groups=all,-notedefault,-device,-darwin,-x86,-mips
repo sync
