#!/bin/bash

sudo apt-get install -y wget

MANIFEST=git://github.com/ProjectSakura/android.git
BRANCH=11

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name zubairk22oct
git config --global user.email areeb9670@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync

git clone https://github.com/zubairk22oct/android_device_xiaomi_rolex -b r device/xiaomi/rolex
git clone https://github.com/Thagoo/android_vendor_xiaomi_rolex -b r vendor/xiaomi/rolex

